version: '3.3'

services:
  install-clever:
    image: maven:3.8.4-openjdk-8
    container_name: install-clever
    volumes:
      - ./:/app/clever
      - /var/.m2:/root/.m2
    working_dir: /app/clever